# Generated by Django 5.2.11 on 2026-03-09 20:52

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='VectorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='core_api.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='core_api.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='core_api_ve_organiz_41e6c0_idx')],
            },
        ),
    ]
