# Generated by Django 5.2.11 on 2026-03-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
