# Generated by Django 5.2.11 on 2026-03-09 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_member_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='linking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
