# Generated by Django 5.2.11 on 2026-03-09 22:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_member_linking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorentry',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
    ]
