# Generated by Django 5.2.11 on 2026-03-10 00:04

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_alter_vectorentry_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorentry',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
