# Generated by Django 5.2.11 on 2026-03-11 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_alter_vectorentry_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Público (Qualquer visitante na internet)'), ('INTERNAL', 'Interno (Todos da mesma Organização)'), ('PRIVATE', 'Privado (Apenas eu e Administradores)')], default='INTERNAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='vectorentry',
            name='core_api_ve_organiz_41e6c0_idx',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='document',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vectorentry',
            name='organization',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='core_api.organization'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core_api.knowledgebase'),
        ),
        migrations.AddField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core_api.knowledgebase'),
        ),
        migrations.AddField(
            model_name='vectorentry',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='core_api.knowledgebase'),
        ),
        migrations.AddIndex(
            model_name='vectorentry',
            index=models.Index(fields=['knowledge_base'], name='core_api_ve_knowled_15d47e_idx'),
        ),
    ]
